n_runs = 1

arguments = [
  "env_args.map_name=5m_vs_6m",
  "t_max=5_000_000",
]

[[runs]]
config = "vdn"
arguments = [
  "name=vdn"
]

[[runs]]
config = "qmix"
arguments = [
  "name=qmix",
]

[[runs]]
config = "qplex"
arguments = [
  "name=qplex",
]

[[runs]]
config = "qfix_sum"
arguments = [
  "name=qfix-sum",
]

[[runs]]
config = "qfix_mono"
arguments = [
  "name=qfix-mono",
]

[[runs]]
config = "qfix_sum_alt"
arguments = [
  "name=qfix-sum-alt",
]
