
env: pettingzoo

test_greedy: True
test_nepisode: 1
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 500000

env_args:
  map_name: SimpleSpread
  episode_limit: 25 # this is not parsed into the inner env yet
  seed: 1998

